/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "GatewayFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "RateLimitTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UpstreamApiUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}